SELECT
  repo.id AS repo_id,
  repo.name as repo_name
FROM
  `githubarchive.month.202505` -- Query a recent month
WHERE
  repo.name in (
    'tensorflow/tensorflow',
'electron/electron',
'facebook/react-native',
'microsoft/terminal',
'godotengine/godot',
'bitcoin/bitcoin',
'opencv/opencv',
'tesseract-ocr/tesseract',
'ocornut/imgui',
'grpc/grpc',
'x64dbg/x64dbg',
'angular/angular',
'microsoft/vscode',
'vuejs/core',
'hoppscotch/hoppscotch',
'n8n-io/n8n',
'nestjs/nest',
'puppeteer/puppeteer',
'Eugeny/tabby',
'microsoft/TypeScript',
'vitejs/vite',
'apache/spark',
'spring-projects/spring-kafka',
'apache/dubbo',
'apache/ignite',
'elastic/elasticsearch-java',
'apache/hadoop',
'apache/cassandra-java-driver',
'apache/zeppelin',
'apache/beam',
'spring-projects/spring-boot',
'huggingface/transformers',
'localstack/localstack',
'keras-team/keras',
'ansible/ansible',
'scikit-learn/scikit-learn',
'tiangolo/fastapi',
'django/django',
'FuelLabs/fuel-core',
'rust-lang/rust',
'tauri-apps/tauri',
'rustdesk/rustdesk',
'alacritty/alacritty',
'comfyanonymous/ComfyUI',
'home-assistant/core',
'unionlabs/union',
'astral-sh/uv',
'FuelLabs/sway',
'denoland/deno',
'zed-industries/zed'
  )
GROUP BY
  repo.id, repo.name
